# Frontend (React + Vite)
FROM node:20-alpine as build

WORKDIR /app

COPY pivoteer-frontend/package*.json ./
RUN npm install

COPY pivoteer-frontend/ .
RUN npm run build

# Serve built app with nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
