# Backend (Spring Boot)
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY src /app/src
COPY build.gradle.kts settings.gradle.kts gradlew /app/
COPY gradle /app/gradle

RUN ./gradlew clean build --no-daemon

EXPOSE 8080

CMD ["java", "-jar", "/app/build/libs/pivoteer-0.0.1-SNAPSHOT.jar"]
